name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Still using v3, but this warning will persist until action updates.

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Ensure we use a supported version
        with:
          node-version: '20'  # Explicitly set to Node.js 20

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli --global

      - name: Authenticate with Salesforce Org
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > sfdx-auth.json
          sfdx auth:sfdxurl:store -f sfdx-auth.json -s  # Use updated flag

      - name: Deploy to Salesforce Org
        run: |
          sfdx force:source:deploy -p force-app/ --wait 10
