name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Updated to use the latest version

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli --global

      - name: Authenticate with Salesforce Org
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > sfdx-auth.json
          sfdx auth:sfdxurl:store -f sfdx-auth.json -s  # Use updated flag

      - name: Deploy to Salesforce Org
        run: |
          sfdx force:source:deploy -p force-app/ --wait 10
